# Generated by Django 3.2.13 on 2022-06-16 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='이메일')),
            ],
            options={
                'db_table': 'AdminUser',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('nick_name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='이메일')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='UserTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='이름')),
                ('tire', models.CharField(choices=[('일반유저', 'Normaluserl'), ('뿜뿜유저', 'Vipuser')], default='일반유저', max_length=10)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualboard.userinformation')),
            ],
            options={
                'db_table': 'usertire',
            },
        ),
        migrations.AddIndex(
            model_name='userinformation',
            index=models.Index(fields=['username', 'email'], name='userinfo_usernam_52d7cf_idx'),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='adminusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='adminusers',
            index=models.Index(fields=['email', 'full_name'], name='AdminUser_email_aafe30_idx'),
        ),
    ]
