# Generated by Django 3.2.13 on 2022-06-04 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminusers',
            name='created_by',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
