# Generated by Django 3.2.13 on 2022-06-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualboard', '0002_adminusers_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminusers',
            name='is_admin',
        ),
    ]
