version: '3.9'

services:
  backend:
    container_name: admin-django
    build: 
      context: ./adminbackend
      dockerfile: Dockerfile
    command: gunicorn adminboard.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./adminbackend/:/adminbackend
      - static-volume:/adminbackend/.static_root
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - sql

  sql:
    container_name: admin-sql
    image: mysql
    ports:
      - "3307:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USERNAME=${DB_USERNAME}
      - TZ=Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-server=utf8mb4
      - --lower_case_table_names=1
    volumes:
      - .sqlVolume:/var/lib/mysql

  ngnix:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: admin-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/con.f/nginx-setup.conf
      - static-volume:/adminbackend/.static_root/

    depends_on:
      - backend


volumes:
  mysql:
  backend:
  build_file:
  static-volume:
